// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super_Cartes_Infinies.Data;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521162019_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111112",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8864f433-545b-4f0b-bb4c-c8e35bbbe7f0",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIrC6uEx0LW8oVPDMouAmCWO0ujMEKJ8pZZXbnldWXYlik+Bdq2tFc5AElJ1y2n3Mg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0982798a-e636-4618-a34e-d7a3b4d447b1",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "User1Id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18e32594-4c12-452a-96b5-d4c21caaed38",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3602232-e742-4391-ba31-6f53d9b2ebbc",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "User2Id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a8b9588-eef6-443c-bf68-fa7f7bfbb5cd",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ce570975-3e88-4581-8a69-6c9c177bec05",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111111",
                            RoleId = "11111111-1111-1111-1111-111111111112"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Models.CardPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("PowerId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PowerId");

                    b.ToTable("cardPowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            PowerId = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            PowerId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 3,
                            CardId = 3,
                            PowerId = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            PowerId = 4,
                            Value = 5
                        });
                });

            modelBuilder.Entity("Models.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Models.Models.DeckCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("OwnedCardid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("OwnedCardid");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("Models.Models.GameConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("QtManaParTour")
                        .HasColumnType("int");

                    b.Property<int>("nbCardsToDraw")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("GameConfigs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            QtManaParTour = 3,
                            nbCardsToDraw = 4
                        });
                });

            modelBuilder.Entity("Models.Models.OwnedCards", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("playerId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CardId");

                    b.HasIndex("playerId");

                    b.ToTable("OwnedCard");
                });

            modelBuilder.Entity("Models.Models.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasValue")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Power");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permet à une carte d’attaquer en « premier » et de ne pas recevoir de dégât si elle tue la carte de l’adversaire.",
                            HasValue = false,
                            Icon = "🥇",
                            Name = "First Strike",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorsqu’une carte défend, elle inflige X de dégâts AVANT de recevoir des dégâts. Si l’attaquant est tué par ces dégâts, l’attaque s’arrête et le défenseur ne reçoit pas de dégâts.",
                            HasValue = true,
                            Icon = "🌹",
                            Name = "Thorns",
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soigne les cartes alliées de X incluant elle-même AVANT d’attaquer (mais les cartes ne peuvent pas avoir plus de health qu’au départ.)",
                            HasValue = true,
                            Icon = "💖",
                            Name = "Heal",
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Augmente la défense d'une carte de X",
                            HasValue = true,
                            Icon = "🛡️",
                            Name = "Shield",
                            Value = 0
                        });
                });

            modelBuilder.Entity("Models.Models.StartingCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardID");

                    b.ToTable("StartingCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardID = 1
                        },
                        new
                        {
                            Id = 2,
                            CardID = 4
                        },
                        new
                        {
                            Id = 3,
                            CardID = 6
                        },
                        new
                        {
                            Id = 4,
                            CardID = 5
                        },
                        new
                        {
                            Id = 5,
                            CardID = 3
                        },
                        new
                        {
                            Id = 6,
                            CardID = 10
                        },
                        new
                        {
                            Id = 7,
                            CardID = 5
                        },
                        new
                        {
                            Id = 8,
                            CardID = 3
                        },
                        new
                        {
                            Id = 9,
                            CardID = 10
                        });
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 4,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
                            Name = "Bulbizarre"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 5,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png",
                            Name = "Herbizarre"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 6,
                            Cost = 5,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
                            Name = "Florizarre"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 7,
                            Cost = 2,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
                            Name = "Salamèche"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 3,
                            Cost = 3,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png",
                            Name = "Reptincel"
                        },
                        new
                        {
                            Id = 6,
                            Attack = 4,
                            Cost = 4,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
                            Name = "Dracaufeu"
                        },
                        new
                        {
                            Id = 7,
                            Attack = 5,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
                            Name = "Carapuce"
                        },
                        new
                        {
                            Id = 8,
                            Attack = 6,
                            Cost = 2,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png",
                            Name = "Carabaffe"
                        },
                        new
                        {
                            Id = 9,
                            Attack = 7,
                            Cost = 3,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
                            Name = "Tortank"
                        },
                        new
                        {
                            Id = 10,
                            Attack = 3,
                            Cost = 4,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png",
                            Name = "Chenipan"
                        },
                        new
                        {
                            Id = 11,
                            Attack = 4,
                            Cost = 5,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png",
                            Name = "Chrysacier"
                        },
                        new
                        {
                            Id = 12,
                            Attack = 5,
                            Cost = 2,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png",
                            Name = "Papilusion"
                        },
                        new
                        {
                            Id = 13,
                            Attack = 6,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png",
                            Name = "Aspicot"
                        },
                        new
                        {
                            Id = 14,
                            Attack = 7,
                            Cost = 4,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png",
                            Name = "Coconfort"
                        },
                        new
                        {
                            Id = 15,
                            Attack = 3,
                            Cost = 5,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png",
                            Name = "Dardargnan"
                        },
                        new
                        {
                            Id = 16,
                            Attack = 4,
                            Cost = 2,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png",
                            Name = "Roucool"
                        },
                        new
                        {
                            Id = 17,
                            Attack = 5,
                            Cost = 3,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png",
                            Name = "Roucoups"
                        },
                        new
                        {
                            Id = 18,
                            Attack = 6,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
                            Name = "Roucarnage"
                        },
                        new
                        {
                            Id = 19,
                            Attack = 7,
                            Cost = 5,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png",
                            Name = "Rattata"
                        },
                        new
                        {
                            Id = 20,
                            Attack = 3,
                            Cost = 2,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png",
                            Name = "Rattatac"
                        },
                        new
                        {
                            Id = 21,
                            Attack = 4,
                            Cost = 3,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png",
                            Name = "Piafabec"
                        },
                        new
                        {
                            Id = 22,
                            Attack = 5,
                            Cost = 4,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png",
                            Name = "Rapasdepic"
                        },
                        new
                        {
                            Id = 23,
                            Attack = 6,
                            Cost = 5,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png",
                            Name = "Abo"
                        },
                        new
                        {
                            Id = 24,
                            Attack = 7,
                            Cost = 2,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png",
                            Name = "Arbok"
                        },
                        new
                        {
                            Id = 25,
                            Attack = 3,
                            Cost = 3,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
                            Name = "Pikachu"
                        },
                        new
                        {
                            Id = 26,
                            Attack = 4,
                            Cost = 4,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
                            Name = "Raichu"
                        },
                        new
                        {
                            Id = 27,
                            Attack = 5,
                            Cost = 5,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png",
                            Name = "Sabelette"
                        },
                        new
                        {
                            Id = 28,
                            Attack = 6,
                            Cost = 2,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png",
                            Name = "Sablaireau"
                        },
                        new
                        {
                            Id = 29,
                            Attack = 7,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png",
                            Name = "Nidoran♀"
                        },
                        new
                        {
                            Id = 30,
                            Attack = 3,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png",
                            Name = "Nidorina"
                        },
                        new
                        {
                            Id = 31,
                            Attack = 4,
                            Cost = 5,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png",
                            Name = "Nidoqueen"
                        },
                        new
                        {
                            Id = 32,
                            Attack = 5,
                            Cost = 2,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png",
                            Name = "Nidoran♂"
                        },
                        new
                        {
                            Id = 33,
                            Attack = 6,
                            Cost = 3,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png",
                            Name = "Nidorino"
                        },
                        new
                        {
                            Id = 34,
                            Attack = 7,
                            Cost = 4,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png",
                            Name = "Nidoking"
                        },
                        new
                        {
                            Id = 35,
                            Attack = 3,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png",
                            Name = "Mélofée"
                        },
                        new
                        {
                            Id = 36,
                            Attack = 4,
                            Cost = 2,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png",
                            Name = "Mélodelfe"
                        },
                        new
                        {
                            Id = 37,
                            Attack = 5,
                            Cost = 3,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png",
                            Name = "Goupix"
                        },
                        new
                        {
                            Id = 38,
                            Attack = 6,
                            Cost = 4,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png",
                            Name = "Feunard"
                        },
                        new
                        {
                            Id = 39,
                            Attack = 7,
                            Cost = 5,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png",
                            Name = "Rondoudou"
                        },
                        new
                        {
                            Id = 40,
                            Attack = 3,
                            Cost = 2,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png",
                            Name = "Grodoudou"
                        },
                        new
                        {
                            Id = 41,
                            Attack = 4,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png",
                            Name = "Nosferapti"
                        },
                        new
                        {
                            Id = 42,
                            Attack = 5,
                            Cost = 4,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png",
                            Name = "Nosferalto"
                        },
                        new
                        {
                            Id = 43,
                            Attack = 6,
                            Cost = 5,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png",
                            Name = "Mystherbe"
                        },
                        new
                        {
                            Id = 44,
                            Attack = 7,
                            Cost = 2,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png",
                            Name = "Ortide"
                        },
                        new
                        {
                            Id = 45,
                            Attack = 3,
                            Cost = 3,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png",
                            Name = "Rafflesia"
                        },
                        new
                        {
                            Id = 46,
                            Attack = 4,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png",
                            Name = "Paras"
                        },
                        new
                        {
                            Id = 47,
                            Attack = 5,
                            Cost = 5,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png",
                            Name = "Parasect"
                        },
                        new
                        {
                            Id = 48,
                            Attack = 6,
                            Cost = 2,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png",
                            Name = "Mimitoss"
                        },
                        new
                        {
                            Id = 49,
                            Attack = 7,
                            Cost = 3,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png",
                            Name = "Aéromite"
                        },
                        new
                        {
                            Id = 50,
                            Attack = 3,
                            Cost = 4,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png",
                            Name = "Taupiqueur"
                        },
                        new
                        {
                            Id = 51,
                            Attack = 4,
                            Cost = 5,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png",
                            Name = "Triopikeur"
                        },
                        new
                        {
                            Id = 52,
                            Attack = 5,
                            Cost = 2,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
                            Name = "Miaouss"
                        },
                        new
                        {
                            Id = 53,
                            Attack = 6,
                            Cost = 3,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png",
                            Name = "Persian"
                        },
                        new
                        {
                            Id = 54,
                            Attack = 7,
                            Cost = 4,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png",
                            Name = "Psykokwak"
                        },
                        new
                        {
                            Id = 55,
                            Attack = 3,
                            Cost = 5,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png",
                            Name = "Akwakwak"
                        },
                        new
                        {
                            Id = 56,
                            Attack = 4,
                            Cost = 2,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png",
                            Name = "Férosinge"
                        },
                        new
                        {
                            Id = 57,
                            Attack = 5,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png",
                            Name = "Colossinge"
                        },
                        new
                        {
                            Id = 58,
                            Attack = 6,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png",
                            Name = "Caninos"
                        },
                        new
                        {
                            Id = 59,
                            Attack = 7,
                            Cost = 5,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png",
                            Name = "Arcanin"
                        },
                        new
                        {
                            Id = 60,
                            Attack = 3,
                            Cost = 2,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png",
                            Name = "Ptitard"
                        },
                        new
                        {
                            Id = 61,
                            Attack = 4,
                            Cost = 3,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png",
                            Name = "Têtarte"
                        },
                        new
                        {
                            Id = 62,
                            Attack = 5,
                            Cost = 4,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png",
                            Name = "Tartard"
                        },
                        new
                        {
                            Id = 63,
                            Attack = 6,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png",
                            Name = "Abra"
                        },
                        new
                        {
                            Id = 64,
                            Attack = 7,
                            Cost = 2,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png",
                            Name = "Kadabra"
                        },
                        new
                        {
                            Id = 65,
                            Attack = 3,
                            Cost = 3,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
                            Name = "Alakazam"
                        },
                        new
                        {
                            Id = 66,
                            Attack = 4,
                            Cost = 4,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png",
                            Name = "Machoc"
                        },
                        new
                        {
                            Id = 67,
                            Attack = 5,
                            Cost = 5,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png",
                            Name = "Machopeur"
                        },
                        new
                        {
                            Id = 68,
                            Attack = 6,
                            Cost = 2,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png",
                            Name = "Mackogneur"
                        },
                        new
                        {
                            Id = 69,
                            Attack = 7,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png",
                            Name = "Chétiflor"
                        },
                        new
                        {
                            Id = 70,
                            Attack = 3,
                            Cost = 4,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png",
                            Name = "Boustiflor"
                        },
                        new
                        {
                            Id = 71,
                            Attack = 4,
                            Cost = 5,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png",
                            Name = "Empiflor"
                        },
                        new
                        {
                            Id = 72,
                            Attack = 5,
                            Cost = 2,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png",
                            Name = "Tentacool"
                        },
                        new
                        {
                            Id = 73,
                            Attack = 6,
                            Cost = 3,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png",
                            Name = "Tentacruel"
                        },
                        new
                        {
                            Id = 74,
                            Attack = 7,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png",
                            Name = "Racaillou"
                        },
                        new
                        {
                            Id = 75,
                            Attack = 3,
                            Cost = 5,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png",
                            Name = "Gravalanch"
                        },
                        new
                        {
                            Id = 76,
                            Attack = 4,
                            Cost = 2,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png",
                            Name = "Grolem"
                        },
                        new
                        {
                            Id = 77,
                            Attack = 5,
                            Cost = 3,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png",
                            Name = "Ponyta"
                        },
                        new
                        {
                            Id = 78,
                            Attack = 6,
                            Cost = 4,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png",
                            Name = "Galopa"
                        },
                        new
                        {
                            Id = 79,
                            Attack = 7,
                            Cost = 5,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png",
                            Name = "Ramoloss"
                        },
                        new
                        {
                            Id = 80,
                            Attack = 3,
                            Cost = 2,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png",
                            Name = "Flagadoss"
                        },
                        new
                        {
                            Id = 81,
                            Attack = 4,
                            Cost = 3,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png",
                            Name = "Magnéti"
                        },
                        new
                        {
                            Id = 82,
                            Attack = 5,
                            Cost = 4,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png",
                            Name = "Magnéton"
                        },
                        new
                        {
                            Id = 83,
                            Attack = 6,
                            Cost = 5,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png",
                            Name = "Canarticho"
                        },
                        new
                        {
                            Id = 84,
                            Attack = 7,
                            Cost = 2,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png",
                            Name = "Doduo"
                        },
                        new
                        {
                            Id = 85,
                            Attack = 3,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png",
                            Name = "Dodrio"
                        },
                        new
                        {
                            Id = 86,
                            Attack = 4,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png",
                            Name = "Otaria"
                        },
                        new
                        {
                            Id = 87,
                            Attack = 5,
                            Cost = 5,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png",
                            Name = "Lamantine"
                        },
                        new
                        {
                            Id = 88,
                            Attack = 6,
                            Cost = 2,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png",
                            Name = "Tadmorv"
                        },
                        new
                        {
                            Id = 89,
                            Attack = 7,
                            Cost = 3,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png",
                            Name = "Grotadmorv"
                        },
                        new
                        {
                            Id = 90,
                            Attack = 3,
                            Cost = 4,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png",
                            Name = "Kokiyas"
                        },
                        new
                        {
                            Id = 91,
                            Attack = 4,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png",
                            Name = "Crustabri"
                        },
                        new
                        {
                            Id = 92,
                            Attack = 5,
                            Cost = 2,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png",
                            Name = "Fantominus"
                        },
                        new
                        {
                            Id = 93,
                            Attack = 6,
                            Cost = 3,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png",
                            Name = "Spectrum"
                        },
                        new
                        {
                            Id = 94,
                            Attack = 7,
                            Cost = 4,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png",
                            Name = "Ectoplasma"
                        },
                        new
                        {
                            Id = 95,
                            Attack = 3,
                            Cost = 5,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png",
                            Name = "Onix"
                        },
                        new
                        {
                            Id = 96,
                            Attack = 4,
                            Cost = 2,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png",
                            Name = "Soporifik"
                        },
                        new
                        {
                            Id = 97,
                            Attack = 5,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png",
                            Name = "Hypnomade"
                        },
                        new
                        {
                            Id = 98,
                            Attack = 6,
                            Cost = 4,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png",
                            Name = "Krabby"
                        },
                        new
                        {
                            Id = 99,
                            Attack = 7,
                            Cost = 5,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png",
                            Name = "Krabboss"
                        },
                        new
                        {
                            Id = 100,
                            Attack = 3,
                            Cost = 2,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png",
                            Name = "Voltorbe"
                        },
                        new
                        {
                            Id = 101,
                            Attack = 4,
                            Cost = 3,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png",
                            Name = "Électrode"
                        },
                        new
                        {
                            Id = 102,
                            Attack = 5,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png",
                            Name = "Noeunoeuf"
                        },
                        new
                        {
                            Id = 103,
                            Attack = 6,
                            Cost = 5,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png",
                            Name = "Noadkoko"
                        },
                        new
                        {
                            Id = 104,
                            Attack = 7,
                            Cost = 2,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png",
                            Name = "Osselait"
                        },
                        new
                        {
                            Id = 105,
                            Attack = 3,
                            Cost = 3,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png",
                            Name = "Ossatueur"
                        },
                        new
                        {
                            Id = 106,
                            Attack = 4,
                            Cost = 4,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png",
                            Name = "Kicklee"
                        },
                        new
                        {
                            Id = 107,
                            Attack = 5,
                            Cost = 5,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png",
                            Name = "Tygnon"
                        },
                        new
                        {
                            Id = 108,
                            Attack = 6,
                            Cost = 2,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png",
                            Name = "Excelangue"
                        },
                        new
                        {
                            Id = 109,
                            Attack = 7,
                            Cost = 3,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png",
                            Name = "Smogo"
                        },
                        new
                        {
                            Id = 110,
                            Attack = 3,
                            Cost = 4,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png",
                            Name = "Smogogo"
                        },
                        new
                        {
                            Id = 111,
                            Attack = 4,
                            Cost = 5,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png",
                            Name = "Rhinocorne"
                        },
                        new
                        {
                            Id = 112,
                            Attack = 5,
                            Cost = 2,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png",
                            Name = "Rhinoféros"
                        },
                        new
                        {
                            Id = 113,
                            Attack = 6,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png",
                            Name = "Leveinard"
                        },
                        new
                        {
                            Id = 114,
                            Attack = 7,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png",
                            Name = "Saquedeneu"
                        },
                        new
                        {
                            Id = 115,
                            Attack = 3,
                            Cost = 5,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png",
                            Name = "Kangourex"
                        },
                        new
                        {
                            Id = 116,
                            Attack = 4,
                            Cost = 2,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png",
                            Name = "Hypotrempe"
                        },
                        new
                        {
                            Id = 117,
                            Attack = 5,
                            Cost = 3,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png",
                            Name = "Hypocéan"
                        },
                        new
                        {
                            Id = 118,
                            Attack = 6,
                            Cost = 4,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png",
                            Name = "Poissirène"
                        },
                        new
                        {
                            Id = 119,
                            Attack = 7,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png",
                            Name = "Poissoroy"
                        },
                        new
                        {
                            Id = 120,
                            Attack = 3,
                            Cost = 2,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png",
                            Name = "Stari"
                        },
                        new
                        {
                            Id = 121,
                            Attack = 4,
                            Cost = 3,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png",
                            Name = "Staross"
                        },
                        new
                        {
                            Id = 122,
                            Attack = 5,
                            Cost = 4,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png",
                            Name = "M. Mime"
                        },
                        new
                        {
                            Id = 123,
                            Attack = 6,
                            Cost = 5,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png",
                            Name = "Insécateur"
                        },
                        new
                        {
                            Id = 124,
                            Attack = 7,
                            Cost = 2,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png",
                            Name = "Lippoutou"
                        },
                        new
                        {
                            Id = 125,
                            Attack = 3,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png",
                            Name = "Élektek"
                        },
                        new
                        {
                            Id = 126,
                            Attack = 4,
                            Cost = 4,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png",
                            Name = "Magmar"
                        },
                        new
                        {
                            Id = 127,
                            Attack = 5,
                            Cost = 5,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png",
                            Name = "Scarabrute"
                        },
                        new
                        {
                            Id = 128,
                            Attack = 6,
                            Cost = 2,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png",
                            Name = "Tauros"
                        },
                        new
                        {
                            Id = 129,
                            Attack = 7,
                            Cost = 3,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png",
                            Name = "Magicarpe"
                        },
                        new
                        {
                            Id = 130,
                            Attack = 3,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png",
                            Name = "Léviator"
                        },
                        new
                        {
                            Id = 131,
                            Attack = 4,
                            Cost = 5,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png",
                            Name = "Lokhlass"
                        },
                        new
                        {
                            Id = 132,
                            Attack = 5,
                            Cost = 2,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png",
                            Name = "Métamorph"
                        },
                        new
                        {
                            Id = 133,
                            Attack = 6,
                            Cost = 3,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png",
                            Name = "Évoli"
                        },
                        new
                        {
                            Id = 134,
                            Attack = 7,
                            Cost = 4,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png",
                            Name = "Aquali"
                        },
                        new
                        {
                            Id = 135,
                            Attack = 3,
                            Cost = 5,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png",
                            Name = "Voltali"
                        },
                        new
                        {
                            Id = 136,
                            Attack = 4,
                            Cost = 2,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png",
                            Name = "Pyroli"
                        },
                        new
                        {
                            Id = 137,
                            Attack = 5,
                            Cost = 3,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png",
                            Name = "Porygon"
                        },
                        new
                        {
                            Id = 138,
                            Attack = 6,
                            Cost = 4,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png",
                            Name = "Amonita"
                        },
                        new
                        {
                            Id = 139,
                            Attack = 7,
                            Cost = 5,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png",
                            Name = "Amonistar"
                        },
                        new
                        {
                            Id = 140,
                            Attack = 3,
                            Cost = 2,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png",
                            Name = "Kabuto"
                        },
                        new
                        {
                            Id = 141,
                            Attack = 4,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png",
                            Name = "Kabutops"
                        },
                        new
                        {
                            Id = 142,
                            Attack = 5,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png",
                            Name = "Ptéra"
                        },
                        new
                        {
                            Id = 143,
                            Attack = 6,
                            Cost = 5,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png",
                            Name = "Ronflex"
                        },
                        new
                        {
                            Id = 144,
                            Attack = 7,
                            Cost = 2,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png",
                            Name = "Artikodin"
                        },
                        new
                        {
                            Id = 145,
                            Attack = 3,
                            Cost = 3,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png",
                            Name = "Électhor"
                        },
                        new
                        {
                            Id = 146,
                            Attack = 4,
                            Cost = 4,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png",
                            Name = "Sulfura"
                        },
                        new
                        {
                            Id = 147,
                            Attack = 5,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png",
                            Name = "Minidraco"
                        },
                        new
                        {
                            Id = 148,
                            Attack = 6,
                            Cost = 2,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png",
                            Name = "Draco"
                        },
                        new
                        {
                            Id = 149,
                            Attack = 7,
                            Cost = 3,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
                            Name = "Dracolosse"
                        },
                        new
                        {
                            Id = 150,
                            Attack = 3,
                            Cost = 4,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
                            Name = "Mewtwo"
                        },
                        new
                        {
                            Id = 151,
                            Attack = 4,
                            Cost = 5,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png",
                            Name = "Mew"
                        },
                        new
                        {
                            Id = 152,
                            Attack = 5,
                            Cost = 2,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/152.png",
                            Name = "Germignon"
                        },
                        new
                        {
                            Id = 153,
                            Attack = 6,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/153.png",
                            Name = "Macronium"
                        },
                        new
                        {
                            Id = 154,
                            Attack = 7,
                            Cost = 4,
                            Health = 4,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/154.png",
                            Name = "Méganium"
                        },
                        new
                        {
                            Id = 155,
                            Attack = 3,
                            Cost = 5,
                            Health = 5,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/155.png",
                            Name = "Héricendre"
                        },
                        new
                        {
                            Id = 156,
                            Attack = 4,
                            Cost = 2,
                            Health = 6,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/156.png",
                            Name = "Feurisson"
                        },
                        new
                        {
                            Id = 157,
                            Attack = 5,
                            Cost = 3,
                            Health = 7,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/157.png",
                            Name = "Typhlosion"
                        },
                        new
                        {
                            Id = 158,
                            Attack = 6,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/158.png",
                            Name = "Kaiminus"
                        },
                        new
                        {
                            Id = 159,
                            Attack = 7,
                            Cost = 5,
                            Health = 9,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/159.png",
                            Name = "Crocrodil"
                        },
                        new
                        {
                            Id = 160,
                            Attack = 3,
                            Cost = 2,
                            Health = 10,
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/160.png",
                            Name = "Aligatueur"
                        });
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMatchCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlayerATurn")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerDataAId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDataBId")
                        .HasColumnType("int");

                    b.Property<string>("UserAId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserBId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDataAId");

                    b.HasIndex("PlayerDataBId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.MatchPlayerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayersData");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.PlayableCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int?>("MatchPlayerDataId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchPlayerDataId1")
                        .HasColumnType("int");

                    b.Property<int?>("MatchPlayerDataId2")
                        .HasColumnType("int");

                    b.Property<int?>("MatchPlayerDataId3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("MatchPlayerDataId");

                    b.HasIndex("MatchPlayerDataId1");

                    b.HasIndex("MatchPlayerDataId2");

                    b.HasIndex("MatchPlayerDataId3");

                    b.ToTable("PlayableCard");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ELO")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ELO = 1000,
                            Name = "Test player 1",
                            UserId = "User1Id"
                        },
                        new
                        {
                            Id = 2,
                            ELO = 1000,
                            Name = "Test player 2",
                            UserId = "User2Id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Models.CardPower", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany("CardPowers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.Power", "Power")
                        .WithMany("cardPowers")
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Power");
                });

            modelBuilder.Entity("Models.Models.Deck", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Player", null)
                        .WithMany("Decks")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Models.Models.DeckCards", b =>
                {
                    b.HasOne("Models.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.OwnedCards", "OwnedCard")
                        .WithMany()
                        .HasForeignKey("OwnedCardid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("OwnedCard");
                });

            modelBuilder.Entity("Models.Models.OwnedCards", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Super_Cartes_Infinies.Models.Player", "player")
                        .WithMany("OwnedCards")
                        .HasForeignKey("playerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("player");
                });

            modelBuilder.Entity("Models.Models.StartingCards", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Match", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", "PlayerDataA")
                        .WithMany()
                        .HasForeignKey("PlayerDataAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", "PlayerDataB")
                        .WithMany()
                        .HasForeignKey("PlayerDataBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlayerDataA");

                    b.Navigation("PlayerDataB");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.MatchPlayerData", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.PlayableCard", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("BattleField")
                        .HasForeignKey("MatchPlayerDataId");

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("CardsPile")
                        .HasForeignKey("MatchPlayerDataId1");

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("Graveyard")
                        .HasForeignKey("MatchPlayerDataId2");

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("Hand")
                        .HasForeignKey("MatchPlayerDataId3");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Player", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Models.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("Models.Models.Power", b =>
                {
                    b.Navigation("cardPowers");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Card", b =>
                {
                    b.Navigation("CardPowers");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.MatchPlayerData", b =>
                {
                    b.Navigation("BattleField");

                    b.Navigation("CardsPile");

                    b.Navigation("Graveyard");

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Player", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("OwnedCards");
                });
#pragma warning restore 612, 618
        }
    }
}
